import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Engine, seedDatabase, classify, defaultPolicy, effectiveDwell, nextDeadline, escalationReducer, scoreAudience, searchKnowledge, notificationChannel, digestDue, policySchema, type KnowledgeItem } from '../src/index';
const now=Date.parse('2026-09-20T06:00:00Z');
function setup(user_id='arisha',time_scale=1){const db=seedDatabase(now);return {db,e:new Engine(db,{user_id,now,time_scale})};}
test('known question returns a cited answer and notifies nobody',async()=>{const {db,e}=setup();const before=db.notifications.length;const result=await e.create({space_id:'cse4790',body_text:'Does anyone have the CSE 4790 Week 6 slides?'});assert.equal(result.agent_outcome,'SERVE');assert.equal(result.request.state,'ANSWERED_BY_KB');assert.ok(result.answer?.cited_item_ids.length);assert.equal(db.notifications.length,before);assert.equal(result.audience_preview.count,0);});
test('new question routes and fast clock walks T1 → T2 → T4 → approval',async()=>{const {db,e}=setup('arisha',3600);const result=await e.create({space_id:'cse4790',body_text:'How does a quantum mutex protect a distributed satellite ledger?'});const r=result.request;assert.equal(r.audience_tier,'T1');assert.equal(Date.parse(r.next_escalation_at!)-now,6000);for(const tier of ['T2','T4']){e.ctx.now=Date.parse(r.next_escalation_at!);e.sweep(r.space_id);assert.equal(r.audience_tier,tier);}e.ctx.now=Date.parse(r.next_escalation_at!);e.sweep(r.space_id);assert.equal(r.state,'AWAITING_APPROVAL');assert.equal(db.approval_tasks.length,1);assert.equal(db.notifications.filter(n=>n.user_id==='nasrin').length,0);const events=db.request_events.length;e.sweep();assert.equal(db.request_events.length,events);});
test('authority skips peers, and a CR must approve before instructor notification',async()=>{const {db,e}=setup();const result=await e.create({space_id:'cse4790',body_text:'Can we get a deadline extension for the Lab 3 report?'});const r=result.request;assert.equal(r.audience_tier,'T4');assert.deepEqual(r.skipped_tiers,['T1','T2','T3']);assert.deepEqual(r.responder_ids,['rifat']);e.ctx.now=Date.parse(r.next_escalation_at!);e.sweep();const approval=db.approval_tasks.find(a=>a.request_id===r.id)!;await assert.rejects(()=>e.handle('POST',`/approvals/${approval.id}/decide`,{decision:'approve'}),/role/);e.ctx.user_id='rifat';await e.handle('POST',`/approvals/${approval.id}/decide`,{decision:'approve'});assert.equal(r.audience_tier,'T5');assert.ok(db.notifications.some(n=>n.user_id==='nasrin'&&n.payload.request_id===r.id));});
test('changing policy leaves the in-flight snapshot and deadline untouched',async()=>{const {e}=setup();const r=(await e.create({space_id:'cse4790',body_text:'Explain distributed satellite memory barriers'})).request;const saved=JSON.stringify(r.policy_snapshot),deadline=r.next_escalation_at;e.ctx.user_id='rifat';await e.handle('PUT','/spaces/cse4790/pace',{preset:'Fast'});const p=await e.handle('GET','/spaces/cse4790/escalation-policy') as ReturnType<typeof defaultPolicy>;p.steps[0].dwell_minutes=120;await e.handle('PUT','/spaces/cse4790/escalation-policy',p);assert.equal(JSON.stringify(r.policy_snapshot),saved);assert.equal(r.next_escalation_at,deadline);});
test('duplicate offer sends no notifications; merge leaves parent clock unchanged',async()=>{const {db,e}=setup();const before=db.notifications.length;const result=await e.create({space_id:'cse4790',body_text:'Where can our group get feedback on the training poster?'});assert.equal(result.agent_outcome,'DUPLICATE_PROMPT');assert.equal(db.notifications.length,before);const parent=db.requests.find(r=>r.id==='open-horizontal')!;const due=parent.next_escalation_at;await e.handle('POST',`/requests/${parent.id}/follow`,{request_id:result.request.id});assert.equal(parent.next_escalation_at,due);assert.equal(result.request.state,'MERGED');assert.equal(parent.merged_count,5);e.ctx.user_id='rifat';const message=e.message(parent.id,{body:'Bring the poster to Tuesday’s consultation.'});e.ctx.user_id='arisha';e.accept(parent.id,{message_id:message.id});assert.ok(db.notifications.some(n=>n.user_id==='st1'&&n.event_type==='request.resolved'));assert.ok(result.request.resolved_at);});
test('authored card requires no request and becomes a sourced instant answer',async()=>{const {db,e}=setup('rifat');db.requests=[];db.messages=[];db.knowledge_items=[];db.notifications=[];const card=await e.handle('POST','/spaces/cse4790/knowledge/cards',{question:'Which colour folder holds the internship checklist?',body:'The internship checklist is in the orange folder.',category:'INFORMATION',expires_in_days:21,notify_space:false}) as KnowledgeItem;assert.equal(card.status,'VERIFIED');assert.equal(card.origin,'AUTHORED');assert.equal(card.source_request_id,null);assert.equal(db.notifications.length,0);e.ctx.user_id='arisha';const outcome=await e.create({space_id:'cse4790',body_text:card.title});assert.equal(outcome.agent_outcome,'SERVE');assert.equal(outcome.answer?.cited_item_ids[0],card.id);});
test('harvest publishes information unverified but gates sensitive material',async()=>{const {db,e}=setup();const r=(await e.create({space_id:'cse4790',body_text:'Where is the zirconium training checklist?',reject_knowledge:true})).request;e.ctx.user_id='rifat';const message=e.message(r.id,{body:'The checklist is on the training board.'});e.ctx.user_id='arisha';e.accept(r.id,{message_id:message.id});const card=db.knowledge_items.find(k=>k.source_request_id===r.id)!;assert.equal(card.status,'UNVERIFIED');assert.equal(card.published,true);e.ctx.user_id='rifat';await e.handle('POST',`/knowledge/${card.id}/verify`);assert.equal(card.status,'VERIFIED');});
test('student cannot invoke CR-only operations and non-member cannot read another hub',async()=>{const {db,e}=setup();await assert.rejects(()=>e.handle('POST','/spaces/cse4790/knowledge/pins',{title:'A',url:'https://example.edu',category:'MATERIAL'}),/role/);await assert.rejects(()=>e.handle('PUT','/spaces/cse4790/pace',{preset:'Fast'}),/role/);// Derived, not hardcoded: which ids land in which hub shifts whenever the seed's account list changes.
const outsider=db.space_memberships.find(m=>m.space_id==='cse4712'&&!db.space_memberships.some(x=>x.space_id==='cse4790'&&x.user_id===m.user_id))?.user_id;assert.ok(outsider,'seed must contain a member of cse4712 who is not in cse4790');e.ctx.user_id=outsider;await assert.rejects(()=>e.handle('GET','/requests/open-horizontal'),/not a member/);await assert.rejects(()=>e.handle('GET','/spaces/cse4790/knowledge'),/not a member/);await assert.rejects(()=>e.handle('GET','/knowledge/card-1'),/not a member/);});
test('lazy reads advance due requests even with no cron',async()=>{const {e}=setup();const r=(await e.create({space_id:'cse4790',body_text:'Explain zirconium mutex ordering',reject_knowledge:true})).request;e.ctx.now=Date.parse(r.next_escalation_at!);await e.handle('GET',`/requests/${r.id}`);assert.equal(r.audience_tier,'T2');});
test('a reply or claim grants grace; following does not',async()=>{const {e}=setup();const r=e.request('open-horizontal'),grace=r.grace_until;await e.handle('POST',`/requests/${r.id}/follow`,{});assert.equal(r.grace_until,grace);e.ctx.user_id='rifat';e.message(r.id,{body:'I am checking the schedule.'});assert.equal(Date.parse(r.grace_until!)-now,45*60000);e.ctx.now=now+60000;r.next_escalation_at=new Date(now).toISOString();assert.equal(escalationReducer(r,r.policy_snapshot,e.ctx.now).action,'WAIT');});
test('quiet hours push P1–P3 forward; P0 ignores them; dwell has a floor and ceiling',()=>{assert.equal(effectiveDwell(1,'P0'),20);assert.equal(effectiveDwell(5000,'P3'),4320);const p=defaultPolicy('s','KNOWLEDGE',now);p.steps[0].dwell_minutes=60;const evening=Date.parse('2026-09-20T16:30:00Z');assert.equal(nextDeadline(evening,'T1','P2',p),'2026-09-21T01:00:00.000Z');assert.equal(nextDeadline(evening,'T1','P0',p),'2026-09-20T16:50:00.000Z');});
test('routing excludes instructors and reserves two low-notification slots',()=>{const {db}=setup();const members=db.space_memberships.filter(m=>m.space_id==='cse4790');const scored=scoreAudience(members,members.find(m=>m.user_id==='arisha')!,['slide','report'],now);assert.equal(scored.tier,'T1');assert.equal(scored.shortlist.length,10);assert.equal(scored.shortlist.filter(x=>x.terms.fairness).length,2);assert.ok(scored.shortlist.every(x=>x.member.role!=='INSTRUCTOR'&&x.member.user_id!=='arisha'));const cold=scored.shortlist.find(x=>x.member.accepted_tags.length===0);if(cold)assert.equal(cold.terms.topic_affinity,.25);});
test('stale knowledge never auto-serves even on an exact title match',()=>{const {db}=setup();const card=db.knowledge_items.find(k=>k.status==='STALE')!;const hits=searchKnowledge(db.knowledge_items,card.space_id,card.title,card.category,now);assert.ok(hits.find(h=>h.item.id===card.id)!.score<.78);});
test('notification overflow becomes a digest and T2 is always batched except P0',()=>{const {db,e}=setup();const before=db.notifications.length;const r=e.request('open-authority');for(let i=0;i<7;i++)e.notify(r,'rifat','request.routed_to_you','Update');assert.equal(db.notifications[before+6].delivered_channel,'DIGEST');assert.equal(notificationChannel([],'arisha','cse4790','T2','P2',now),'DIGEST');assert.equal(notificationChannel([],'arisha','cse4790','T2','P0',now),'PUSH');db.notifications[before+6].delivered_at=new Date(now).toISOString();assert.equal(digestDue(db.notifications,'rifat','cse4790',now+3600000),false);});
test('classifier downgrades unsupported urgency and never fabricates authority decisions',async()=>{const c=await classify('Please share the slides',{code:'CSE 4790',priority_requested:'P0'});assert.equal(c.priority_suggested,'P2');assert.equal(c.category,'MATERIAL');const a=await classify('Projector broken in room 3',{code:'CSE 4790'});assert.equal(a.request_class,'AUTHORITY');const fallback=await classify('question',{code:'CSE 4790'},{name:'invalid',classify:async()=>({})});assert.equal(fallback.needs_review,true);});
test('policy validation rejects automatic instructor or department escalation',()=>{const p=defaultPolicy('s','AUTHORITY',now);p.steps[1].requires_approval=false;assert.equal(policySchema.safeParse(p).success,false);});
test('instructor lock prevents CR pace changes',async()=>{const {e}=setup('nasrin');await e.handle('PATCH','/spaces/cse4790',{policy_locked:true});e.ctx.user_id='rifat';await assert.rejects(()=>e.handle('PUT','/spaces/cse4790/pace',{preset:'Fast'}),/instructor/);});
test('kill switch sends new questions to CR and disables autonomous sweep',async()=>{const {e,db}=setup('nasrin');await e.handle('PATCH','/spaces/cse4790',{agent_enabled:false});e.ctx.user_id='arisha';const r=(await e.create({space_id:'cse4790',body_text:'Does anyone have the CSE 4790 Week 6 slides?'})).request;assert.equal(r.audience_tier,'T4');e.ctx.now=Date.parse(r.next_escalation_at!);e.sweep();assert.equal(db.approval_tasks.length,0);});
