import { SignJWT, jwtVerify } from 'jose';
import { createHash, randomBytes } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { DomainError, Engine, inputSchemas, requireRole, type SpaceRole } from '@peerloop/core';
import { database } from '../db/client';
import { transact } from './store';
const issuer='peerloop';
function key(){const value=process.env.JWT_SECRET;if(!value||value.length<32)throw new DomainError('CONFIG','Set JWT_SECRET to at least 32 random characters.',503);return new TextEncoder().encode(value);}
export async function mint(user_id:string){return new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(user_id).setIssuer(issuer).setAudience('peerloop-client').setIssuedAt().setExpirationTime('30d').sign(key());}
export async function authenticate(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token)throw new DomainError('UNAUTHENTICATED','Sign in to continue.',401);try{const {payload}=await jwtVerify(token,key(),{issuer,audience:'peerloop-client',algorithms:['HS256']});if(!payload.sub)throw new Error('Missing subject');return payload.sub;}catch(e){if(e instanceof DomainError)throw e;throw new DomainError('UNAUTHENTICATED','Your session has expired. Sign in again.',401);}}
export function withAuth(handler:(req:Request,user_id:string)=>Promise<Response>,options:{role?:Exclude<SpaceRole,'STUDENT'>;space_id?:(req:Request)=>string}={}){return async(req:Request)=>{const user_id=await authenticate(req);if(options.role&&options.space_id){await transact(db=>{const e=new Engine(db,{user_id,now:Date.now()});requireRole(e.membership(options.space_id!(req)),options.role!);});}return handler(req,user_id);};}
export async function authRoute(path:string,req:Request,body:unknown){
  if(path==='dev-login'){if(process.env.NODE_ENV==='production')throw new DomainError('NOT_FOUND','Not found.',404);const {studentId}=inputSchemas.devLogin.parse(body);const user=await transact(db=>db.users.find(u=>u.student_id===studentId));if(!user)throw new DomainError('NOT_FOUND','Run the seed command before demo login.',404);return {token:await mint(user.id),user};}
  if(path==='request-link'){const {email}=inputSchemas.magicLink.parse(body);const domain=email.split('@')[1].toLowerCase();if(!(process.env.INSTITUTIONAL_DOMAINS??'iut-dhaka.edu').split(',').includes(domain))throw new DomainError('EMAIL_DOMAIN','Use your institutional email address.');const db=database();const recent=await db.execute(sql`select count(*)::int as count from auth_links where email=${email.toLowerCase()} and created_at>now()-interval '1 hour'`);if(Number(recent[0]?.count)>=3)throw new DomainError('RATE_LIMIT','Please wait before requesting another sign-in link.',429);const token=randomBytes(32).toString('hex'),hash=createHash('sha256').update(token).digest('hex');await db.execute(sql`insert into auth_links(id,email,expires_at,created_at) values(${hash},${email.toLowerCase()},now()+interval '15 minutes',now())`);const link=`${process.env.APP_URL??'peerloop://'}${(process.env.APP_URL??'peerloop://').endsWith('/')?'':'/'}sign-in?token=${encodeURIComponent(token)}`;if(!process.env.EMAIL_WEBHOOK_URL)throw new DomainError('EMAIL_CONFIG','Configure EMAIL_WEBHOOK_URL for magic-link delivery.',503);const response=await fetch(process.env.EMAIL_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.EMAIL_WEBHOOK_SECRET??''}`},body:JSON.stringify({to:email,subject:'Your PeerLoop sign-in link',text:`Sign in to PeerLoop. This one-use link expires in 15 minutes: ${link}`}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new DomainError('EMAIL_DELIVERY','Email delivery failed. Please try again later.',502);return {ok:true};}
  if(path==='verify'){const {token}=inputSchemas.verifyLink.parse(body);const hash=createHash('sha256').update(token).digest('hex');const db=database();const links=await db.execute(sql`update auth_links set used_at=now() where id=${hash} and used_at is null and expires_at>now() returning email`);if(!links.length)throw new DomainError('INVALID_LINK','This sign-in link expired or was already used.',401);const user=await transact(state=>{const u=state.users.find(u=>u.email.toLowerCase()===links[0].email);if(!u)throw new DomainError('NOT_INVITED','Ask your course representative to add you to the roster.',403);state.space_memberships.filter(m=>m.user_id===u.id).forEach(m=>m.status='ACTIVE');return u;});return {token:await mint(user.id),user};}
  if(path==='refresh'){const id=await authenticate(req);return {token:await mint(id)};}
  throw new DomainError('NOT_FOUND','Auth endpoint not found.',404);
}
