import type { Database, Request, SpaceMembership, User } from './types';
import { defaultPolicy, nextDeadline } from './escalation/dwell';
import { tokenize } from './knowledge/search';
export const demoAccounts=[{studentId:'ARISHA',name:'Arisha',role:'Student'},{studentId:'RIFAT',name:'Rifat',role:'Class representative'},{studentId:'NASRIN',name:'Dr. Nasrin',role:'Instructor'},{studentId:'ADMIN',name:'Department admin',role:'Department'}];
export function seedDatabase(now:number):Database{
  const iso=new Date(now).toISOString(),ago=(days:number)=>new Date(now-days*86400000).toISOString();
  const users:User[]=[...demoAccounts,{studentId:'KAMAL',name:'Dr. Kamal',role:'Instructor'},...Array.from({length:39},(_,i)=>({studentId:`ST${i+1}`,name:['Tahsin','Nabila','Sami','Farhan','Maliha','Raihan','Sadia','Fahim','Nafisa','Adnan','Labib','Mim','Sakib'][i%13]+` ${i+1}`,role:'Student'}))].map(u=>({id:u.studentId.toLowerCase(),student_id:u.studentId,name:u.name,email:`${u.studentId.toLowerCase()}@iut-dhaka.edu`,avatar_initials:u.name.split(' ').map(s=>s[0]).slice(0,2).join(''),active_space_id:'cse4790',push_tokens:[],preferences:{theme:'system',leaderboard:false,notifications:true,tags_only:false,tags:[],quiet_start:'23:00',quiet_end:'07:00'},created_at:ago(30)}));
  const spaces=[{id:'cse4790',org_id:'iut-cse',kind:'COURSE' as const,code:'CSE 4790',title:'Industrial Training',term:'2026-Fall',section:'Batch 47 · Sec A',color_token:'flare' as const,join_code:'4790-A7KQ',allow_sibling_relay:false,agent_enabled:true,pace_override:1,policy_locked:false,archived_at:null},{id:'cse4712',org_id:'iut-cse',kind:'COURSE' as const,code:'CSE 4712',title:'Software Engineering',term:'2026-Fall',section:'Batch 47 · Sec A',color_token:'indigo' as const,join_code:'4712-B9LP',allow_sibling_relay:false,agent_enabled:true,pace_override:1,policy_locked:false,archived_at:null}];
  const memberships:SpaceMembership[]=spaces.flatMap((s,k)=>users.filter(u=>!['admin',k===0?'kamal':'nasrin'].includes(u.id)).slice(0,k===0?38:41).map((u,i)=>({id:`${s.id}-${u.id}`,space_id:s.id,user_id:u.id,role:u.id==='rifat'?'CR':['nasrin','kamal'].includes(u.id)?'INSTRUCTOR':'STUDENT',joined_at:ago(28),helper_score:.3+i%8*.07,verified_helper:i%5===0,notified_count_7d:i%11,accepted_answers_30d:i%8,notified_count_30d:5+i%17,last_active_at:ago(i%6*.3),muted_until:null,lab_group:i%3===0?'A':'B',section:s.section,notification_budget_override:null,notifications_sent_today:i%3,accepted_tags:i%4===0?[]:i%2===0?['slide','report','submit','format','week','itr']:['algorithm','project','lab','group','code'],status:'ACTIVE',creation_muted_until:null})));
  const db:Database={users,org_memberships:[{user_id:'admin',org_id:'iut-cse',role:'DEPT_ADMIN'}],spaces,space_memberships:memberships,requests:[],request_events:[],request_recipients:[],messages:[],knowledge_items:[],escalation_policies:spaces.flatMap(s=>(['KNOWLEDGE','AUTHORITY','HYBRID'] as const).map(c=>defaultPolicy(s.id,c,now))),approval_tasks:[],notifications:[],agent_runs:[]};
  const refs=[['Week 6 lecture slides','Week 6 slides are in the Classroom material post after Tuesday’s lecture.'],['Industrial training handbook','Read the training objectives, attendance expectations and supervisor sign-off guidance.'],['ITR report template','Use this template for the cover page, weekly log and final reflection.'],['Weekly progress log','Update your weekly log before meeting your supervisor.'],['Assessment rubric','The rubric covers participation, report quality and the final presentation.'],['Presentation schedule','Check your allocated presentation slot and arrive ten minutes early.'],['Supervisor consultation hours','Consultations are on Tuesday afternoon by appointment.'],['Classroom course stream','Official announcements and materials are in the course stream.'],['Report formatting guide','Submit a single PDF, with numbered pages and readable figures.'],['Attendance register','Review your attendance with the course representative.'],['Training evaluation form','Ask your supervisor to complete the training evaluation.'],['Final presentation guide','Prepare a concise demonstration with evidence of your work.']];
  refs.forEach(([title,body],i)=>db.knowledge_items.push({id:`pin-${i+1}`,space_id:'cse4790',kind:'PINNED_REF',title,body_markdown:body,url:`https://classroom.google.com/`,category:'MATERIAL',status:'VERIFIED',origin:'AUTHORED',source_request_id:null,contributor_ids:['rifat'],pin_order:i,expires_at:new Date(now+21*86400000).toISOString(),last_retrieved_at:null,retrieval_hits:i%5,false_positive_count:0,created_by:'rifat',created_at:ago(4),tags:tokenize(title),published:true,previously_verified:true}));
  const cards=[['Does anyone have the CSE 4790 Week 6 slides?','The Week 6 slides were posted after Tuesday’s lecture. Open the pinned Week 6 lecture slides reference.'],['What format should the ITR report use?','Submit one PDF using the report template. Number your pages and include the supervisor’s signature.'],['How is the final grade weighted?','The assessment rubric in Classroom is the authoritative reference for the final grade breakdown.'],['How long is the final presentation?','Prepare an eight-minute demonstration followed by two minutes of questions.'],['Who signs the training log?','Your placement supervisor signs the weekly log; the course teacher reviews the completed record.'],['Can I include screenshots in the report?','Yes. Add a caption to each screenshot and explain what it demonstrates.'],['How do I acknowledge my team?','Add a contribution statement that describes each member’s individual work.'],['What goes in the reflection section?','Describe what you learned, one challenge you addressed and what you would improve next time.'],['Where can I find a sample weekly log?','The weekly progress log reference includes an example entry.']];
  cards.forEach(([title,body],i)=>db.knowledge_items.push({id:`card-${i+1}`,space_id:'cse4790',kind:'ANSWER_CARD',title,body_markdown:body,url:null,category:i===0?'MATERIAL':'INFORMATION',status:i===5||i===6?'STALE':i<7?'VERIFIED':'UNVERIFIED',origin:i<3?'AUTHORED':'HARVESTED',source_request_id:i<3?null:`resolved-${i-2}`,contributor_ids:['rifat'],pin_order:null,expires_at:i===5||i===6?ago(1):new Date(now+21*86400000).toISOString(),last_retrieved_at:ago(i),retrieval_hits:10-i,false_positive_count:0,created_by:'rifat',created_at:ago(7),tags:tokenize(title),published:true,previously_verified:i<7}));
  db.knowledge_items.push({...db.knowledge_items[12],id:'se-proposal',space_id:'cse4712',title:'Where is the software engineering proposal link?',body_markdown:'Submit the proposal through the Software Engineering Classroom assignment named Project proposal.',tags:['software','proposal','submit','link'],retrieval_hits:2});
  function request(id:string,body:string,state:Request['state'],tier:Request['audience_tier'],space_id='cse4790',author='arisha'):Request{const cls=tier==='T4'?'AUTHORITY':'KNOWLEDGE';const policy=defaultPolicy(space_id,cls,now);const r:Request={id,space_id,author_id:author,body_text:body,normalised_question:body,category:cls==='AUTHORITY'?'LOGISTICS_AUTHORITY':'INFORMATION',request_class:cls,priority:'P2',tags:tokenize(body),audience_tier:tier,state,parent_request_id:null,merged_count:1,policy_snapshot:policy,next_escalation_at:state==='RESOLVED'?null:nextDeadline(now,tier,'P2',policy),grace_until:null,responder_ids:[],accepted_answer_id:null,resolved_at:state==='RESOLVED'?ago(1):null,closed_reason:null,contains_personal_info:false,needs_review:false,skipped_tiers:cls==='AUTHORITY'?['T1','T2','T3']:[],held_reason:null,attempt:0,created_at:ago(2),updated_at:iso};db.requests.push(r);db.request_events.push({id:`event-${id}`,request_id:id,from_state:'CHECKING',to_state:state,tier,actor_type:'SYSTEM',actor_id:null,reason:cls==='AUTHORITY'?'Skipped the peer stages: this needs approval, not knowledge.':'Asked the smallest relevant audience.',dedupe_key:`${id}:${tier}:0`,at:ago(2)});return r;}
  for(let i=0;i<6;i++){const r=request(`resolved-${i+1}`,i<4?'Where do we submit the ITR report?':cards[i][0],'RESOLVED',i%2?'T1':'T4');r.request_class='KNOWLEDGE';r.skipped_tiers=[];r.accepted_answer_id=`answer-${i+1}`;db.messages.push({id:r.accepted_answer_id,request_id:r.id,author_id:'rifat',author_type:'USER',body_markdown:i<4?'Submit through the ITR report assignment in Classroom.':cards[i][1],cited_item_ids:[],is_accepted:true,created_at:ago(1.9)});}
  const horizontal=request('open-horizontal','Where can our group get feedback on the training poster?','ESCALATED','T2');
  horizontal.responder_ids=memberships.filter(m=>m.space_id==='cse4790'&&m.role!=='INSTRUCTOR'&&m.user_id!=='arisha').map(m=>m.user_id);
  horizontal.merged_count=4;
  horizontal.responder_ids.forEach(user_id=>db.request_recipients.push({request_id:horizontal.id,user_id,tier:'T2',notified_at:ago(.2),opened_at:null,responded_at:null,score_snapshot:null}));
  request('open-authority','Can we get a Lab 3 deadline extension?','ROUTED','T4');
  for(let i=0;i<3;i++){const r=request(`merged-${i+1}`,horizontal.body_text,'MERGED','T2','cse4790',`st${i+1}`);r.parent_request_id=horizontal.id;r.next_escalation_at=null;}
  request('se-open','How does dependency inversion improve our project architecture?','ROUTED','T1','cse4712','st3');
  db.request_recipients.push({request_id:'se-open',user_id:'arisha',tier:'T1',notified_at:iso,opened_at:null,responded_at:null,score_snapshot:null});
  return db;
}
