export type SpaceRole = 'STUDENT' | 'CR' | 'INSTRUCTOR';
export type OrgRole = 'DEPT_ADMIN' | 'SYS_ADMIN';
export type RequestClass = 'KNOWLEDGE' | 'AUTHORITY' | 'HYBRID';
export type Category = 'MATERIAL' | 'INFORMATION' | 'ACADEMIC_HELP' | 'COORDINATION' | 'LOGISTICS_AUTHORITY' | 'CAMPUS_ISSUE';
export type Priority = 'P0' | 'P1' | 'P2' | 'P3';
export type Tier = 'T0' | 'T1' | 'T2' | 'T3' | 'T4' | 'T5' | 'T6';
export type RequestState = 'DRAFT' | 'CHECKING' | 'ANSWERED_BY_KB' | 'MERGED' | 'ROUTED' | 'IN_PROGRESS' | 'ESCALATED' | 'AWAITING_APPROVAL' | 'RESOLVED' | 'CLOSED_UNRESOLVED';
export type KnowledgeKind = 'PINNED_REF' | 'ANSWER_CARD';
export type KnowledgeStatus = 'UNVERIFIED' | 'VERIFIED' | 'STALE' | 'RETIRED';
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export interface User { org_roles?: OrgMembership[]; id: string; student_id: string; name: string; email: string; avatar_initials: string; active_space_id: string | null; push_tokens: string[]; preferences: { theme: 'system' | 'light' | 'dark'; leaderboard: boolean; notifications: boolean; tags_only: boolean; tags: string[]; quiet_start: string; quiet_end: string }; created_at: string }
export interface OrgMembership { user_id: string; org_id: string; role: OrgRole }
export interface Space { id: string; org_id: string; kind: 'COURSE' | 'BATCH' | 'CLUB' | 'DEPARTMENT'; code: string; title: string; term: string; section: string; color_token: 'flare' | 'sage' | 'indigo' | 'amber' | 'clay'; join_code: string; allow_sibling_relay: boolean; agent_enabled: boolean; pace_override: number; policy_locked: boolean; archived_at: string | null }
export interface SpaceMembership { id: string; space_id: string; user_id: string; role: SpaceRole; joined_at: string; helper_score: number; verified_helper: boolean; notified_count_7d: number; accepted_answers_30d: number; notified_count_30d: number; last_active_at: string; muted_until: string | null; lab_group: string; section: string; notification_budget_override: number | null; notifications_sent_today: number; accepted_tags: string[]; status: 'ACTIVE' | 'PENDING_INVITE'; creation_muted_until: string | null }
export interface PolicyStep { tier: Tier; dwell_minutes: number | null; requires_approval: boolean; manual_only?: boolean }
export interface EscalationPolicy { id: string; space_id: string; request_class: RequestClass; steps: PolicyStep[]; quiet_hours: { start: string; end: string; tz: string; applies_below_priority: Priority }; grace_period_minutes: number; locked_by_instructor: boolean; pace_override: number; final_action: 'CLOSE_UNRESOLVED_WITH_SUMMARY'; updated_by: string | null; updated_at: string; time_scale: number }
export interface Request { id: string; space_id: string; author_id: string; body_text: string; normalised_question: string; category: Category; request_class: RequestClass; priority: Priority; tags: string[]; audience_tier: Tier; state: RequestState; parent_request_id: string | null; merged_count: number; policy_snapshot: EscalationPolicy; next_escalation_at: string | null; grace_until: string | null; responder_ids: string[]; accepted_answer_id: string | null; resolved_at: string | null; closed_reason: string | null; contains_personal_info: boolean; needs_review: boolean; skipped_tiers: Tier[]; held_reason: string | null; attempt: number; created_at: string; updated_at: string }
export interface RequestEvent { id: string; request_id: string; from_state: RequestState; to_state: RequestState; tier: Tier; actor_type: 'USER' | 'AGENT' | 'SYSTEM'; actor_id: string | null; reason: string; dedupe_key: string; at: string }
export interface RequestRecipient { request_id: string; user_id: string; tier: Tier; notified_at: string; opened_at: string | null; responded_at: string | null; score_snapshot: ScoreBreakdown | null }
export interface Message { id: string; request_id: string; author_id: string | null; author_type: 'USER' | 'AGENT'; body_markdown: string; cited_item_ids: string[]; is_accepted: boolean; created_at: string }
export interface KnowledgeItem { id: string; space_id: string; kind: KnowledgeKind; title: string; body_markdown: string; url: string | null; category: Category; status: KnowledgeStatus; origin: 'HARVESTED' | 'AUTHORED' | 'ANNOUNCEMENT'; source_request_id: string | null; contributor_ids: string[]; pin_order: number | null; expires_at: string; last_retrieved_at: string | null; retrieval_hits: number; false_positive_count: number; created_by: string | null; created_at: string; tags: string[]; published: boolean; previously_verified: boolean }
export interface ApprovalTask { id: string; space_id: string; request_id: string | null; kind: 'ESCALATE_TIER' | 'BROADCAST' | 'PUBLISH_CARD' | 'CLOSE_COMPLAINT'; payload: { tier?: Tier; card_id?: string; rationale: string }; requested_by_type: 'USER' | 'AGENT'; assignee_role: SpaceRole | OrgRole; assignee_id: string | null; state: 'PENDING' | 'APPROVED' | 'DECLINED' | 'EXPIRED'; decided_by: string | null; decided_at: string | null; note: string | null }
export interface Notification { id: string; user_id: string; space_id: string; event_type: string; payload: { request_id?: string; card_id?: string; text: string }; read_at: string | null; delivered_channel: 'PUSH' | 'DIGEST' | 'IN_APP'; delivery_state: 'PENDING' | 'SENT' | 'FAILED'; created_at: string; delivered_at: string | null; error: string | null }
export interface AgentRun { id: string; request_id: string; step: string; model: string; prompt_hash: string; output_json: Json; latency_ms: number; tokens_in: number; tokens_out: number; error: string | null; created_at: string }
export interface ScoreBreakdown { topic_affinity: number; responsiveness: number; recent_activity: number; structural_proximity: number; role_bonus: number; load_penalty: number; total: number; fairness: boolean }
export interface Classification { category: Category; request_class: RequestClass; priority_suggested: Priority; priority_reason: string; tags: string[]; normalised_question: string; detected_space_hint: string | null; contains_personal_info: boolean; needs_review?: boolean }
export interface SearchHit { item: KnowledgeItem; score: number; terms: { lexical: number; title: number; tags: number; verified: number; pinned: number; stale: number; age: number } }
export interface CreateOutcome { request: Request; agent_outcome: 'SERVE' | 'SUGGEST' | 'ROUTE' | 'DUPLICATE_PROMPT'; answer?: Message; duplicates?: { request: Request; score: number }[]; audience_preview: { count: number; tier: Tier; next_escalation_at: string | null; steps: PolicyStep[] }; classification: Classification }
export interface Thread { request: Request; timeline: RequestEvent[]; messages: Message[]; recipients: RequestRecipient[]; cards: KnowledgeItem[] }
export interface Database { users: User[]; org_memberships: OrgMembership[]; spaces: Space[]; space_memberships: SpaceMembership[]; requests: Request[]; request_events: RequestEvent[]; request_recipients: RequestRecipient[]; messages: Message[]; knowledge_items: KnowledgeItem[]; escalation_policies: EscalationPolicy[]; approval_tasks: ApprovalTask[]; notifications: Notification[]; agent_runs: AgentRun[] }
export interface SpaceSummary extends Space { role: SpaceRole | OrgRole; unread_count: number; open_count: number; queue_count: number; member_count: number }
export interface Analytics { total: number; open: number; unresolved: number; median_first_response_minutes: number; resolution: { tier: Tier; count: number }[]; origins: { origin: string; count: number }[]; topics: { tag: string; count: number; week: string }[]; recurring: { question: string; count: number; request_ids: string[] }[]; cr_workload: number }
export const terminalStates: RequestState[] = ['RESOLVED', 'CLOSED_UNRESOLVED', 'MERGED'];
