import type { EscalationPolicy, Priority, RequestClass, Tier } from '../types';
export const priorityMultipliers:Record<Priority,number>={P0:.15,P1:.5,P2:1,P3:2};
export function defaultPolicy(space_id:string,request_class:RequestClass,now:number):EscalationPolicy{const dwell=request_class==='HYBRID'?[240,480,720]:[360,1440,1440];return {id:`${space_id}-${request_class}`,space_id,request_class,steps:request_class==='AUTHORITY'?[{tier:'T4',dwell_minutes:720,requires_approval:false},{tier:'T5',dwell_minutes:null,requires_approval:true},{tier:'T6',dwell_minutes:null,requires_approval:true,manual_only:true}]:[{tier:'T1',dwell_minutes:dwell[0],requires_approval:false},{tier:'T2',dwell_minutes:dwell[1],requires_approval:false},{tier:'T4',dwell_minutes:dwell[2],requires_approval:false},{tier:'T5',dwell_minutes:null,requires_approval:true}],quiet_hours:{start:'23:00',end:'07:00',tz:'Asia/Dhaka',applies_below_priority:'P1'},grace_period_minutes:45,locked_by_instructor:false,pace_override:1,final_action:'CLOSE_UNRESOLVED_WITH_SUMMARY',updated_by:null,updated_at:new Date(now).toISOString(),time_scale:1};}
export function effectiveDwell(base:number,priority:Priority,pace=1){return Math.min(4320,Math.max(20,base*priorityMultipliers[priority]*pace));}
function minutesAt(timestamp:number,tz:string){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(timestamp);return Number(parts.find(p=>p.type==='hour')?.value)*60+Number(parts.find(p=>p.type==='minute')?.value);}
export function inQuietHours(timestamp:number,quiet:EscalationPolicy['quiet_hours']){const parse=(t:string)=>Number(t.slice(0,2))*60+Number(t.slice(3));const value=minutesAt(timestamp,quiet.tz),start=parse(quiet.start),end=parse(quiet.end);return start===end?false:start>end?value>=start||value<end:value>=start&&value<end;}
export function nextDeadline(now:number,tier:Tier,priority:Priority,policy:EscalationPolicy):string|null{const step=policy.steps.find(s=>s.tier===tier);if(!step||step.dwell_minutes===null)return null;let due=now+effectiveDwell(step.dwell_minutes,priority,policy.pace_override)*60000/policy.time_scale;
  if(policy.time_scale===1&&priority!=='P0'&&Number(priority[1])>=Number(policy.quiet_hours.applies_below_priority[1])){for(let i=0;i<1440&&inQuietHours(due,policy.quiet_hours);i++)due+=60000;}
  return new Date(due).toISOString();
}
